# name: build-main

# on:
#   push:
#     branches:
#       - autoware
#   pull_request:
#     branches:
#       - autoware
# jobs:
#   load-env:
#     uses: ./.github/workflows/load-env.yaml

#   build-main:
#     needs: load-env
#     runs-on: ubuntu-latest
#     container: ${{ needs.load-env.outputs.base-image }}
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v3

#       - name: Run setup script
#         run: |
#           chmod +x ./setup-dev-env.sh 
#           ./setup-dev-env.sh -y

#       - name: Set git config
#         uses: autowarefoundation/autoware-github-actions/set-git-config@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Run vcs import
#         run: |
#           mkdir src
#           vcs import src < autoware.repos

#       - name: Run vcs export
#         run: |
#           vcs export --exact src || true

#       - name: Run rosdep install
#         run: |
#           sudo apt-get -y update
#           rosdep update
#           DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro ${{ needs.load-env.outputs.rosdistro }}

#       - name: Build
#         run: |
#           . /opt/ros/${{ needs.load-env.outputs.rosdistro }}/setup.sh
#           colcon build --event-handlers console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=Release

name: build-main

on:
  push:
    branches:
      - autoware
  pull_request:
    branches:
      - autoware

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  build-main:
    needs: load-env
    runs-on: ubuntu-latest
    container: ${{ needs.load-env.outputs.base-image }}
    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v3

      - name: Check disk usage
        run: |
          du -sh /* | sort -h

      - name: Check disk space
        run: |
          df -h

      # - name: Cache ROS dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: /opt/ros
      #     key: ros-deps-${{ runner.os }}-${{ hashFiles('**/autoware.repos', '**/simulator.repos') }}
      #     restore-keys: |
      #       ros-deps-${{ runner.os }}-

      - name: Clean space
        run: |
          sudo apt purge \
            ansible \
            apache2 \
            aria2 \
            azure-cli \
            cabal* \
            clang* \
            dotnet-sdk* \
            firefox \
            ghc* \
            google-chrome-stable \
            google-cloud-sdk \
            kubectl \
            libpq-dev \
            microsoft-edge-stable \
            moby-buildx \
            moby-cli \
            moby-compose \
            moby-engine \
            mongodb* \
            mono-complete \
            mysql* \
            nginx \
            node* \
            npm* \
            nuget \
            php* \
            postgresql* \
            powershell \
            r-base \
            rpm \
            ruby* \
            sphinxsearch \
            subversion \
            yarn \
            -yq >/dev/null 2>&1 || true
          sudo apt-get autoremove -y >/dev/null 2>&1 || true
          sudo apt-get autoclean -y >/dev/null 2>&1 || true
          df -h

      - name: Run Setup Script 
        run: |
          chmod +x ./setup-dev-env.sh 
          ./setup-dev-env.sh -y

      - name: Set Git Config  
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Import Main Repositories  
        run: |
          mkdir src
          vcs import src < autoware.repos

      - name: Import Simulator Repositories  
        run: |
          vcs import src < simulator.repos

      - name: Run VCS Export  
        run: |
          vcs export --exact src || true

      - name: Install ROS Dependencies  
        if: steps.cache-ros-deps.outputs.cache-hit != 'true'
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro ${{ needs.load-env.outputs.rosdistro }}

      # - name: Cache build artifacts
      #   id: cache-build-artifacts
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/ros2_ws/build
      #     key: build-artifacts-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.h') }}
      #     restore-keys: |
      #       build-artifacts-${{ runner.os }}-

      - name: Check disk usage
        run: |
          du -sh /* | sort -h

      - name: Check disk space
        run: |
          df -h

      - name: Build Code  
        if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
        run: |
          . /opt/ros/${{ needs.load-env.outputs.rosdistro }}/setup.sh
          colcon build --event-handlers console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=Release

      # - name: Generate Test Configuration  # 生成测试配置文件
      #   run: |
      #     python3 .github/scripts/generate_test_configuration.py

      # - name: Display new_workflow.yaml  # 显示new_workflow.yaml
      #   run: cat test_runner/scenario_test_runner/config/new_workflow.yaml

      # - name: Run Scenario Test  # 运行场景测试
      #   run: |
      #     source /opt/ros/${{ needs.load-env.outputs.rosdistro }}/setup.sh
      #     source install/local_setup.sh
      #     ros2 launch scenario_test_runner scenario_test_runner.launch.py workflow:='/path/to/config/new_workflow.yaml' global_frame_rate:=20
      #     ros2 run scenario_test_runner result_checker.py /tmp/scenario_test_runner/result.junit.xml

